### ISSUE TITLE
"Round already started"

### ISSUE THREAD

**Issue by regulad** [regulad/AdvancementHunt#20]
# "Round already started"
* After a game has started, the plugin does not allow any players to join the server with the message "Round already started."
* This also applies after a game is over.
1. Fix kicking players after a game is over

**Comment by kyematzen** [comment]
Hi, I fixed 1. although 2. will need to be fixed by someone else.

I was unable to check in-game if the option was fixed.
You'll need to reset your messages.yml.

**Comment by regulad** [comment]
> 
> 
> Hi, I fixed 1. although 2. will need to be fixed by someone else.
> 
> I was unable to check in-game if the option was fixed.
> You'll need to reset your messages.yml.
> 
> You can find this in my latest pull request.

thank you kye, very cool
ive changed the issue
